# Generated by Django 3.1.7 on 2021-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_numberofcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pic',
            field=models.ImageField(default='pic1.jpg', upload_to='data/story_pics'),
        ),
    ]
