# Generated by Django 3.1.7 on 2021-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210404_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='pic',
            field=models.ImageField(default='pic1.jpg', upload_to='data/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='slogan',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentuser',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
