# Generated by Django 3.1.7 on 2021-04-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210404_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='pic',
            field=models.ImageField(default='profile.png', upload_to='data/profile_pics/'),
        ),
    ]
